### ISSUE TITLE
Add new Algorithm

### ISSUE THREAD

**Issue by datnguyencse** [onuralparslan/nOBS#1]
Dear @onuralparslan 

Thanks for the awesome nOBS. I have a project with OBS and I have to simulate with the FFUC, LAUC.... but I don't know how and where to start.
Could you please help me.

Thanks you so much.

**Comment by onuralparslan** [comment]
Hi
In order to add a new scheduling algorithm, you can change the code in the file op-schedule.cc

**Comment by datnguyencse** [comment]
I'm going to read the file and trying to understand how that code implement the LAUC-VF algorithm.

Thank you for your time.

**Comment by datnguyencse** [comment]
Hi @onuralparslan 

I install this module to NS2 and it was created two file out.nam and out.tr (ns sim20_7bmulti-cont.tcl), "exec nam out.nam" working, but out.tr was broken with tracegraph202: "Trouble reading number from file (row 8, field 6) ==> OP_BURST       40 ------- 47 0.1 4.-1 -1 41\n"

I think the problem is the number -1: "+ 0.008002 0 1 OP_BURST 40 ------- 47 0.1 4.-1 -1 41"

I didn't change anything in source code.

[out.txt](https://github.com/onuralparslan/nOBS/files/923468/out.txt)

**Comment by onuralparslan** [comment]
Sorry, I have never used tracegraph, so I don't know how it works. Probably, tracegraph does not accept non standard packet types like OP_BURST (optical burst packet), which does not carry output port and sequence number information.

**Comment by datnguyencse** [comment]
So how did you analyze data such as throughput, packet drop ....

**Comment by onuralparslan** [comment]
I had written some scripts that read out.tr file and calculate the stats, but I don't have them anymore.

**Comment by canximan** [comment]
Thanks you, I think I will read the file cont.txt and calculate the packet has drop. Currently, that info is very important to me.

Thanks again.
